### ISSUE TITLE
Fix lag problems

### ISSUE THREAD

**Issue by marvin-bitterlich** [PH111P/powerline#15] opened 2017-04-30 17:15 UTC
Using the bar for longer times makes it have a noticeable delay when switching workspaces.

Some systems have this delay initially.

**Comment by PH111P** [comment] 2017-05-02 10:45
This seems to be a system specific bug.

**Comment by PH111P** [comment] 2017-05-06 11:52
Do you use the powerline-daemon?

**Comment by PH111P** [comment] 2017-06-14 22:42
If you use the powerline-daemon, which client do you use?

**Comment by PH111P** [comment] 2017-07-09 11:38
As I cannot reproduce this issue, and you didn't provide enough details to further look into this, I have to close this issue fur now.

**Closed as completed by PH111P** 2017-07-09 11:38 UTC
